spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tecsacadas
    username: tecsacadas
    password: tecsacadas@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/tecsacadas
    user: tecsacadas
    password: tecsacadas@123

server:
  port: 8081

acompanhamento-leads:
    path: classpath:sheets/acompanhamento-leads/AcompanhamentoDeLeadsTecSacadas.xlsx