spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tecsacadas
    username: tecsacadas
    password: tecsacadas
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/tecsacadas
    user: tecsacadas
    password: tecsacadas
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

acompanhamento-leads:
    path: "classpath:sheets/acompanhamento-leads/Acompanhamento de Leads - Tec Sacadas.xlsx"

cep-api:
    url: https://viacep.com.br/ws

#############################################################################
## OpenApi
#############################################################################
springdoc.default-produces-media-type: application/json
