spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ferna3326_tecsacadas
    username: ferna3326_admin
    password: tecsacadas@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/tecsacadas
    user: tecsacadas
    password: tecsacadas
    encoding: iso-8859-16
  sql:
    init:
      encoding: ISO-8859-16
server:
  port: 3803

acompanhamento-leads:
    path: classpath:sheets/acompanhamento-leads/AcompanhamentoDeLeadsTecSacadas.xlsx

cep-api:
  url: https://viacep.com.br/ws