version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: tecsacadas
      POSTGRES_USER: tecsacadas
      POSTGRES_PASSWORD: tecsacadas@123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: