version: '3'

services:
  tecsacadas-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tecsacadas@123
      MYSQL_USER: tecsacadas
      MYSQL_PASSWORD: tecsacadas
      MYSQL_DATABASE: tecsacadas
    volumes:
      - tecsacadas_database:/var/lib/mysql

volumes:
  tecsacadas_database: