version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tecsacadas@123
      MYSQL_USER: tecsacadas
      MYSQL_PASSWORD: tecsacadas
      MYSQL_DATABASE: tecsacadas
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: